---
- hosts: all
  tasks:
  - name: make direcotry
    file:
      path: "/home/worker/.ssh"
      state: directory
  - name: create empty file
    file:
      path: "/home/worker/.ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/worker/.ssh/authorized_keys"
      line: "foo"