---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: make directory
    file:
      path: "/home/<user>/.ssh"
      state: directory
  - name: put pubkey
    lineinfile:
      path: "/home/<user>/.ssh/authorized_keys"
      line: "foo"
      create: yes
  - name: visudo
    lineinfile:
      path: "/etc/sudoers.d/<user>"
      line: "<user> ALL=(ALL) NOPASSWD:ALL"
      create: yes
